### ISSUE TITLE
incompatible with Save our Ship 2

### ISSUE THREAD

**Issue by dcar2019** [emipa606/ImpassableFurniture#1]
ImpassableFurniture seems to cause hull tiles from SoS2 to allow pawns to walk over them, and it also prevents pressurization of rooms for SoS2 purposes.  Thain#4108 has been notified in thier Discord, so you two can work it out when/if you'd like to do that.

Save our Ship 2 steam page: https://steamcommunity.com/sharedfiles/filedetails/?id=1909914131

**Comment by emipa606** [comment]
Should work better now: 452ff23
